### ISSUE TITLE
Global Modifiers - Bear School

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#1]
We currently have the Wolf School (no penalty to Strong Stikes) and Viper School (no penalty to Joint Strikes), but the Bear School (-2 to EV) isn't there. There are the Armored Caster (-1 to EV for Spellcasting, Ritual Crafting, Hex Weaving) and a -1 to Armor Penalty option (not sure what for), but there is no -2 for the Bear School.

**Comment by Stexinator** [comment]
Instead of a specific ``Bear School`` I made the generic ``-1 to Armor Penalty`` so homebrew and other feature can use that. For Bear School you would just add ``-1 to Armor Penalty`` twice

**Comment by Siryphas** [comment]
Weird, but I'll do that.
