### ISSUE TITLE
Armor Global Modifiers

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#105]
Can we get the ability to add global modifiers to armors? There aren't many that require it, but some of the Elderfolk and the relic armors need them.

**Comment by Stexinator** [comment]
Do you need special modifiers?

I am adding core foundry active effects which can do what former the non-special part of global modifiers can do

**Comment by Stexinator** [comment]
@Siryphas can you guess if active effects would fulfill this purpose? Then I will enable it for armor

**Comment by Siryphas** [comment]
Probably? I'm not very familiar with the new content, but it should.
