### ISSUE TITLE
Armor Enhancement - All Armor

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#115]
I'm not sure if there's a way to do it, but Armor Enhancements are supposed to apply to all pieces of armor currently worn (as long as they have a free AE slot) by default. Though, you can choose to apply it to only a single piece.
Currently, you have to manually add an Enhancement to each piece, which also requires you to make a version without weight, for additional pieces.

If there is a way to make it so you could choose to apply an Armor Enhancement to the all pieces of armor or just a single piece, that would be great.

**Comment by LinkDragmire** [comment]
In my version (german) of the rulebook, it's not stated, that the enhancement is applied to all pieces worn. It applies to all zones of an armor (like body and arms). Maybe there is a translation error, or a misunderstanding, but i think using the enhancement on different pieces of armor is requirung more than one enhancement.

**Comment by Stexinator** [comment]
Different Enhancements
Enhancements are created and sold as sets. You apply an armor enhancement to every piece of armor that you are wearing at that time. See the sidebar for details on splitting armor enhancements

Parts of Enhancements
You can choose to apply part of an armor enhancement to only one section of your armor, if you want to split hairs. The process is the same, but the enhancement only applies to one body part and you have the other parts to use later.

In the english book, which deepL translates to:

Verschiedene Enhancements
Aufwertungen werden als Sets hergestellt und verkauft. Du wendest eine Rüstungsverbesserung auf jedes Rüstungsteil an, das du zu diesem Zeitpunkt trägst. Details zum Aufteilen von Rüstungsverbesserungen finden Sie in der Seitenleiste

Teile von Verstärkungen
Sie können einen Teil einer Rüstungsverbesserung auch nur auf einen Teil Ihrer Rüstung anwenden, wenn Sie Haare spalten wollen. Der Vorgang ist derselbe, aber die Verbesserung gilt nur für einen Körperteil und du kannst die anderen Teile später verwenden.


Übersetzt mit DeepL.com (kostenlose **Version)**

**Comment by LinkDragmire** [comment]
Ok, reading the original english text, I'm with you.

**Comment by Stexinator** [comment]
The system itself does not handle it very well. I suggest to add 0 weight copies that are applied to other armor pieces. I dont think this will be added to the system in the near future
