### ISSUE TITLE
Damage that ignores armor shouldn't damage the armor

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#117]
Currently, applying damage (via right-clicking the chat box) from a damage roll that ignores armor still causes reliability damage to the armor. It also applies location multipliers to damage, which most such effects ignore (blood drain, suffocation, poison, bleeding, dehydration, etc.)

The second issue is fairly simple to deal with on the player-end (just always select torso when applying damage) but the first issue is a bit less efficient as the player or gm will have to manually correct the armor sp each time, or else just manually apply damage, which is fine, but kind of defeats the purpose of automating the damage in the first place.

Could this checkbox be altered so that applying the damage doesn't deal reliability damage to the armor?

**Comment by Stexinator** [comment]
Do all instances of damage that bypasses armor ignore location?

**Comment by Stexinator** [comment]
@joridin if you want to have the location adressed you can open a new issue where you point to the rules
