### ISSUE TITLE
Crits and Fumbles on Saving Throws

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#129]
Saving Throws, be it STUN Saves or BODY Saves or whatnot, should not be able to roll Crits or Fumbles, and they do.

**To Reproduce**
Roll a saving throw.

**Expected behavior**
It should _not_ crit or fumble.

**Comment by Stexinator** [comment]
I cannot find any rules that say this

**Comment by Siryphas** [comment]
Crits and Fumbles are only for Skill Checks. Saving Throws are not Skill Checks. Additionally a 1 on a Saving Throw is the best you can get, it doesn't make sense for it to Fumble. Likewise a 10 on a Saving Throw is the worst and doesn't make sense to Crit.

CB pg 57
_"If you roll a 1 or a 10 when rolling for a skill check the roll “Explodes”. On a 10, you roll the die once more and add that value to 10 to get your final roll value. On a 1, you must roll again and subtract the second roll from your skill Base. If your second roll is a 10 the roll explodes again (up or down based on whether the first roll was a 1 or a 10)."_
