### ISSUE TITLE
[FEATURE] Active Effects as Modifiers

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#130]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but at the moment, Active Effects reduce the Max Stat and Skill of an actor; it would be easier to keep track of everything if the Active Effects were treated as Modifiers (and had a chat note) instead.

**Describe the solution you'd like**
Adjust Active Effects to be treated as Modifiers and add to chat, explaining what the bonus/penalty is from.

**Comment by Stexinator** [comment]
Molillos UI rework was intended to address this, but there is currently a bug

**Comment by Stexinator** [comment]
For skills this is solved in the next version.
