### ISSUE TITLE
Suggestion: Add Effect Macros to the Wiki

### ISSUE THREAD

**Issue by SquidOfDoomed** [witchertrpg-foundryvtt/TheWitcherTRPG#137]
I saw that you mentioned how to integrate some status effects via Condition lab.

I did create some macros for most effects and published them here: https://www.reddit.com/r/WitcherTRPG/comments/1etn3bp/foundryvtt_macros_for_witcher_status_effects/

Not sure if this could also go into the module but hoping for a mention the wiki at least.

(If too unrefined, since generated via chatgpt or unsafe for whatever reason, some feedback would be great!)

**Comment by Stexinator** [comment]
Someone of them are already integrated in the system via active effects (e.g. staggered)

You can check it here: https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/blob/main/module/setup/config.js#L1840

You can create a module for all the other stuff or open a PR that includes your macros with the system. Adding turn based functionality is wished by some people and that would be a good start

**Comment by SquidOfDoomed** [comment]
Dabbled a bit around today: https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/compare/main...SquidOfDoomed:TheWitcherTRPG:main
Fire was still a bit too complex for me. Added a reminder for that status. What do you think?

**Comment by Stexinator** [comment]
@SquidOfDoomed do you want to give it another try?
