### ISSUE TITLE
[BUG] cannot install module

### ISSUE THREAD

**Issue by GunKra-De** [witchertrpg-foundryvtt/TheWitcherTRPG#139]
When attempting to install this module inside of the Windows desktop version of Foundry, it returns this: **error: [undefined] Cannot read properties of null (reading 'id')**.

**To Reproduce**
1. Go to _Install System_
2. Search for _The Witcher TRPG_
3. click on _install_

**Versions (please complete the following information):**
 - Foundry Version [e.g. v12.331]

**Comment by Stexinator** [comment]
@ortegamarcel can you check the configuration on the foundry site?

**Comment by Stexinator** [comment]
@GunKra-De in the mean while you can try to install it manually with "https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/releases/latest/download/system.json" in the url field

**Comment by GunKra-De** [comment]
Perfect. With the link it worked - thanks!
