### ISSUE TITLE
[BUG] Stats + Bonus only players

### ISSUE THREAD

**Issue by Melkkart** [witchertrpg-foundryvtt/TheWitcherTRPG#144]
Hello, I have noticed an issue (or so I think). If, for example, a character has a statistic of 10 in intelligence, the bonus is 3; both 9 and 10 give a bonus of 3. I believe this is an error. For instance, Player 1 has 5 in swordsmanship, 10 in dexterity, and their dice roll is a 3, which adds 3 (from DEX) + 3 (from the dice) + 5 (from the skill). I have reviewed the rulebook again and have not found anything; everything works correctly with the NPCs. I used the latest version, 12.3, although I don't rule out that it could be my misinterpretation of the rules; I've been thinking about this for hours. Hehe.
Thank you for your excellent work; you have brought this fantastic game to life. A big hug!

**Comment by Stexinator** [comment]
About which bonus are you talking?

**Comment by Melkkart** [comment]
![image](https://github.com/user-attachments/assets/4f1ef46e-01b0-4726-8c73-626e7dae8605)
![image](https://github.com/user-attachments/assets/4c6ad3d3-8ddc-4374-8205-acce68df521f)
In NPC I think it is fine, but in players, INT 5 for example, when making the roll, it should add 5, but it adds 1, if you look at the image it says INT1, which is what 1 adds to the die, It doesn't add up to 5, with a 10 it only adds up to 3 SDP3, sorry for not explaining it well, English is difficult for me.

**Comment by pedroaugustobt** [comment]
Maybe you are at the Wound Threshold @Melkkart, your HP below WT?

**Comment by Melkkart** [comment]
True, I'm an idiot, I got confused with the new format, sorry and thank you very much, I'm closing the Bug

**Comment by pedroaugustobt** [comment]
> True, I'm an idiot, I got confused with the new format, sorry and thank you very much, I'm closing the Bug

no problem bro, the layout has changed and it causes a bit of confusion at first
