### ISSUE TITLE
[BUG] Dialog for spell damage location doesn't display the proper type

### ISSUE THREAD

**Issue by moliloo** [witchertrpg-foundryvtt/TheWitcherTRPG#152]
**Describe the bug**
When i try to apply the damage to a actor, the type of damage appears `WITCHER.Armor.undefined`

**To Reproduce**
1. Roll the magic in Character Sheet and spell it
2. Click on Damage Button in the spell card created in chat fot the spell
3. Right-click in the damage card to apply the damage
4. In the first line of the dialog you can see the error in the `What type of damage:`

**Expected behavior**
Display the proper type of magical damage of the spell

**Screenshots**
![image](https://github.com/user-attachments/assets/77eeb65b-d349-453d-b479-f753e7bddcdc)

**Comment by Stexinator** [comment]
I take suggestions for damage types
