### ISSUE TITLE
[FEATURE] Edit Toxicity Maximum

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#164]
**Is your feature request related to a problem? Please describe.**
To be able to edit the Tox maximum for Witcher who have point in their skill tree that raised their tox max.

**Describe the solution you'd like**
To edit tox max.

**Comment by Stexinator** [comment]
![grafik](https://github.com/user-attachments/assets/90932ce4-55f4-4991-99e8-7901207e6fd0)

The goal is to do most stuff with active effects
