### ISSUE TITLE
[BUG] Casting a Spell/Sign with template doesn't produce chat output

### ISSUE THREAD

**Issue by LinkDragmire** [witchertrpg-foundryvtt/TheWitcherTRPG#167]
We recognized that since the latest updates, casting a spell or a sign with preconfigured template, only uses stamina, but does not end in an chat output.

We recoginzed while trying to use Igni ord Aard with a configured cone. Deactivating the cone in the sign options results in a roll and chat output.

**Comment by Stexinator** [comment]
I tested it in my local dev environment with a fresh character and it works without issue. So I guess something on the character is broken. Can you send me the offending character?

**Comment by LinkDragmire** [comment]
It's happening for more than one character, but I will send one. What do you need exactly?

**Comment by LinkDragmire** [comment]
[fvtt-Actor-relvon-keta-xM1xa1uDnnfMALzN.json](https://github.com/user-attachments/files/17390592/fvtt-Actor-relvon-keta-xM1xa1uDnnfMALzN.json)
here is an export as json

**Comment by Stexinator** [comment]
You are missing an update somehow. Delete all 'm' from the ranges and they work fine.

**Comment by LinkDragmire** [comment]
this solved it! Thanks a lot. Didn't see that. I will close the bug

**Comment by LinkDragmire** [comment]
Yeah, we know. This is some kind of legacy weight (hehe) on our table, because we started without weight restrictions.
