### ISSUE TITLE
Investigation Automation: Evidence Checks

### ISSUE THREAD

**Issue by Stexinator** [witchertrpg-foundryvtt/TheWitcherTRPG#17]
Evidence checks are made by the players as a form of attack against the Mystery's HP, called Complexity. Each clue may have an Obfuscation rating, which works like SP, reducing the damage done by a PC's Evidence check.

**Comment by Stexinator** [comment]
@Siryphas can you give feedback after this is released? If that fits your use case I will add it similiar for obstacles

**Comment by Siryphas** [comment]
Yeah, I'll check it out.
