### ISSUE TITLE
[FEATURE] Clearer Active Modifiers

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#171]
**Is your feature request related to a problem? Please describe.**
The current active modifiers are all in formats such as "system.derivedStats.hp.max" and "system.skills.will.courage.modifiers," would it be possible to make these a little easier to read?

**Describe the solution you'd like**
Rather than "system.derivedStats.hp.max", it could read "HP Max" and for "system.skills.will.courage.modifiers," it could read "WILL - Courage Modifiers," or something to that effect. Make it easier to find what you're looking to adjust.

**Comment by Stexinator** [comment]
This is provided by Foundry. I added a autocomplete so that you dont have to guess the paths.
