### ISSUE TITLE
[BUG] Passive Modifiers for Race Items

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#173]
**Describe the bug**
ActiveEffects applied to Race Item Sheets do not apply when the Race Item is added to an Actor sheet.

**To Reproduce**
Set an Effect for a Race Item Sheet (Dwarf, Elf, etc.)
Apply the Race Item to an Actor Sheet

**Expected behavior**
If Effects are added to a Race Item Sheet and the Race Item Sheet is applied to an Actor Sheet, the Effects from the Race Item Sheet should be applied to the Actor Sheet.
Example: Aen Seidhe/Elves gain a +2 Modifier to Archery. If that Archery +2 Modifier is applied to the Elf Race Item Sheet, the +2 to Archery should be applied to the Actor when equipped with the Elf Race Item.

**Comment by Stexinator** [comment]
![grafik](https://github.com/user-attachments/assets/248c3a9a-39a7-4e72-b41a-4848b192eeab)
![grafik](https://github.com/user-attachments/assets/1212404c-fb74-4381-8612-7d58b3ed4dbf)
![grafik](https://github.com/user-attachments/assets/ac32178a-cd98-407c-a39c-c64925ca7e85)

Works without issue. Foundry removed showing all active effects of items on the actor. I check if I can enable that again
