### ISSUE TITLE
[FEATURE] Balanced as a Weapon Effect

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#176]
**Is your feature request related to a problem? Please describe.**
Now that Critical Wounds have been automated, there is reason to include the Balanced weapon effect.

**Describe the solution you'd like**
Balanced adds +2 to the Critical Hit roll (2d6+2 rather than 2d6), or +1 when aimed (1d6+1 rather than 1d6). This is a small change but can have a large impact on the severity of Critical Wounds.

**Comment by Stexinator** [comment]
I already implemented the targets for active effects for that, so that you can adjust the items accordingly. To enable this in the whole system I need to rework the location targeting which will take a while
