### ISSUE TITLE
[BUG] Homelands no longer give bonuses?

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#191]
**Describe the bug**
I remember that Homelands used to add a bonus automatically, was this removed or is this a BUG?

**Expected behavior**
Homelands should give a bonus based on the Corebook

**Additional context**
This would also be a very convenient way to add the Witcher School Bonuses using the Active Effects system, by adding the Witcher Schools as Homelands and giving their Perk as the bonus for that homeland.
- Dyn Marv Caravan (Cat) - Immune to Non-Magical Charm Attempts
- Haern Cadvch (Bear) - -2 to Overall Armor Penalty
- Kaer Y Seren (Griffin) - +2 Vigor Threshold
- Behelt Nar/Bialsuf Alsarea (Manticore) - Shieldmaster
- Gorthwr Gvaed (Viper) - No Penalties for Dual Wielding
- Kaer Morhen (Wolf) - No Penalty for Strong Strikes

**Comment by Stexinator** [comment]
I dont remember ever touching code there. As far as I remember they never gave a bonus. When I built my character in the system from TechnoAnthro I added the bonus manually.

Can you create two feature requests for this?

- add special modifiers to active effect
- long term: add homelands as items
