### ISSUE TITLE
[BUG] Active Effect - Override

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#209]
**Describe the bug**
The Override function of Active Modifiers seems to add to the value modified rather than override it. For example, Elgan's Bastion reduces an Actor's SPD to 2, but if I place an Override it adds 2 to SPD instead of bringing it to a 2.

**To Reproduce**
1. Add an Active Modifier
2. Modify a value using Override
3. See error

**Expected behavior**
Ideally, when an Active Modifier has an Override it will set the affected STAT/Skill at that value. Ex. A SPD of 5 with an override of 2, will be reduced to 2.

**Comment by Stexinator** [comment]
Ah yeah, that is one of the cases where the modifier should not be targeted but the final value.

**Comment by Siryphas** [comment]
Ah, okay. I've got it working.

**Comment by Stexinator** [comment]
Be aware that modifiers and encumbarance will apply after the reduction
