### ISSUE TITLE
[FEATURE] Active Effects - All Skills Effect

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#210]
**Is your feature request related to a problem? Please describe.**
There aren't many uses, but there are some like the Champion of the River (Veyopatis) Arch-Priest Invocation which gives a +5 to all rolls.

**Describe the solution you'd like**
Have an All Skills option in Active Effects options.

**Comment by Stexinator** [comment]
Ah damn, I thought I can get around this...
