### ISSUE TITLE
How can I create a Region Property in spells?

### ISSUE THREAD

**Issue by pedroaugustobt** [witchertrpg-foundryvtt/TheWitcherTRPG#214]
I have some questions about the new integrated system. I checked the checkbox to create a region, but after casting the spell, the region is not created.
![image](https://github.com/user-attachments/assets/a213fa44-b784-4aba-a8eb-63b45e233c84)

**Comment by Stexinator** [comment]
The region is created from the template. Currently only GMs can create regions. In the next version players can use this functionality too

**Comment by pedroaugustobt** [comment]
> The region is created from the template. Currently only GMs can create regions. In the next version players can use this functionality too

The problem is that the template is created but the region is not, do I need to create the region manually?

**Comment by pedroaugustobt** [comment]
I was stupid xD, the map I was on was not active, the regions were being created on the other map. My bad.
