### ISSUE TITLE
[BUG] Problem dragging item and automatically creating macro in hotbar

### ISSUE THREAD

**Issue by pedroaugustobt** [witchertrpg-foundryvtt/TheWitcherTRPG#217]
**Describe the bug**
It is not possible to create macros by dragging an item from an NPC or player's sheet. A message appears saying "You can only create macro buttons for owned Items"

**Screenshots**
![image](https://github.com/user-attachments/assets/228bb55e-7046-4f5b-be21-562ef6e7b542)

**Versions (please complete the following information):**
 - Foundry Version [e.g. v12.331]
 - TheWitcherTRPG [v12.13.0]

**Comment by Stexinator** [comment]
It still creates the macro. The message is just misleading

**Comment by pedroaugustobt** [comment]
It creates the macro, but this code creates the item roll macro automatically.

**Comment by pedroaugustobt** [comment]
here in TheWitcherTRPG.js
`async function createMacro(data, slot) {
    if (data.type == 'Actor') {
        const actor = game.actors.get(data.id);
        if (!actor) {
            return;
        }
        const command = `game.actors.get('${data.id}')?.sheet.render(true)`;
        let macro = game.macros.entities.find(macro => macro.name === actor.name && macro.command === command);

        if (!macro) {
            macro = await Macro.create(
                {
                    name: actor.name,
                    type: 'script',
                    img: actor.system.img,
                    command: command
                },
                { renderSheet: false }
            );
        }
        game.user.assignHotbarMacro(macro, slot);
        return false;
    } else if (!('item' in data)) {
        return ui.notifications.warn('You can only create macro buttons for owned Items');
    } else if (data.item.type == 'weapon') {
        const weapon = data.item;
        let foundActor = null;
        game.actors.forEach(actor => {
            actor.items.forEach(item => {
                if (weapon._id == item.id) {
                    foundActor = actor;
                }
            });
        });`

**Comment by Stexinator** [comment]
Yeah, that originally never worked. So it should have the same behaviour as always. I added a fix that has the intended functionality

**Comment by pedroaugustobt** [comment]
> I fixed the problems with tokens too and added a workflow for consumables. Anything else you are missing?

That's it.
I'm working on a simple feature that my players want, it's a currency converter, as soon as it's ready, I'll send the pr.
