### ISSUE TITLE
[BUG] Active Effects not fully functional (skill modifiers not working) 

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#222]
**Describe the bug**
Active effect skill modifiers not working.

**To Reproduce**
Create an active effect on a character or monster with a skill modifier (e.g. +1 to Awareness) and then roll the skill it's supposed to apply to. 

**Expected behavior**
Skill modifiers from active effects functional.

**Versions (please complete the following information):**
 - Foundry Version [ v12.331]
 - Version [12.12.0 and 12.13.0]

**Additional context**
I have reproduced the bug in newly created worlds just to ensure it is not a legacy of deleted global modifiers or a byproduct of any modules.

**Comment by Stexinator** [comment]
Did you create the paths via the wizard? That would be a known bug that is fixed in the next release
