### ISSUE TITLE
[BUG] Stuck stat modifiers

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#223]
**Describe the bug**
In v 12.12.0 i deleted all global modifiers and removed them from all actors and items as instructed, only to discover after doing so that the modifiers to base and derived stats lingered. I later discovered that this also applied to character sheets created before12.20.0 that had critical wounds: when deleting the (treated) cracked ribs, say, off of a pc, the penalty to their ENC remained.

**To Reproduce**
If you have a character or monster sheet created before v.12.12.0 that has any stat modifiers from global modifiers, active effects, or critical wounds, those effects will linger after the source of the effect (the wound/global modifier/active effect) remains.

**Expected behavior**
Modifiers disappear after source effect is deleted.

**Screenshots**
![Screenshot 2024-11-21 182416](https://github.com/user-attachments/assets/1e8c6205-950a-4eeb-b6c6-14f106c4aeb2)
![Screenshot 2024-11-21 182449](https://github.com/user-attachments/assets/24604322-84fb-4b85-bc0a-6174e70230cd)
This character has -10 enc from a treated cracked ribs effect, which has since been deleted because it healed in-game.

**Versions (please complete the following information):**
 - Foundry Version 12.331
 - Version 12.12.0 and 12.13.0]

**Additional context**
This problem can be 'solved' by simply recreating character sheets from scratch. Newly created sheets do not have this problem.

**Comment by Stexinator** [comment]
Nice, I was looking for that. Can you send me your actor with the most stats? Then I can fix that in a bunch

**Comment by Stexinator** [comment]
If you want to fix it immediatly you can push an update to the actor that modifies the ``totalModifiers`` of stats. For everything else I need to look into the data

**Comment by joridin** [comment]
this actor has a lingering -3 to int, -3 to ref, -7 to dex, -3 to will from a bunch of deleted critical wounds:
[fvtt-Actor-frigyes-aep-odȍn-(copy)-3hbaU0Jx8eexgkXt.json](https://github.com/user-attachments/files/17866678/fvtt-Actor-frigyes-aep-od.n-.copy.-3hbaU0Jx8eexgkXt.json)

for context, the uncopied version still has the critical wounds:
[fvtt-Actor-obe-(july-11,-1271)-(copy)-P7EorVs7ELBEcSI9.json](https://github.com/user-attachments/files/17866693/fvtt-Actor-obe-.july-11.-1271.-.copy.-P7EorVs7ELBEcSI9.json)
