### ISSUE TITLE
[BUG] Problems with active effect duration

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#224]
**Describe the bug**
First Problem: Creating an active effect with a duration triggered by consuming a consumable seems to not function properly.
Second Problem. Active effects created without durations (i.e. intended to be passive, permanent modifiers) sometimes randomly acquire a durations of 1, causing them to disappear when the actor ends a turn during combat.

**To Reproduce**
First Problem: Create a consumable item that causes an active effect on the consumer. Give it a duration. Have the actor use it and pass the actor through a few turns in combat. Either use up the duration or delete the effect after a few rounds, Using another consumable of the same type will have reduced duration unless you add more rounds to it in the gui. It seems like time used up off of a given consumable effect's duration 'sticks'.
Second Problem: Create or drag passive, no-duration effects on to an actor. Then place their token on a map, or place them into a combat. It does not always happen, and i can't quite predict which ones it will happen to. 

**Expected behavior**
Effects with no duration remaining passive/permanent until manually deleted. Effects with durations lasting as long as they say they should.

**Screenshots**
![Screenshot 2024-11-22 090610](https://github.com/user-attachments/assets/e019ceb8-4a5d-4e51-b610-6c5f03f2097a)
I had to increase the duration to 20 rounds because, due to continued testing, when set to 10, the consumable effect immediately disappeared on use.

**Versions (please complete the following information):**
 - Foundry Version 12.331
 - Version 12.12.0 , 12.13.0 , 12.14.0

**Comment by Stexinator** [comment]
I cannot reproduce it. Can you give further information or provide an export of the item/actor?

**Comment by joridin** [comment]
[fvtt-Actor-vagra-of-zerrikania-VmVf8gZFI1YuahxK.json](https://github.com/user-attachments/files/17878232/fvtt-Actor-vagra-of-zerrikania-VmVf8gZFI1YuahxK.json)
![Screenshot 2024-11-22 191527](https://github.com/user-attachments/assets/38b61df4-a420-4904-8a96-ecdef1b312ea)

Prediction: if placed into a combat and a turn and/or full round is passed, the three effects highlighted by the red circle will vanish. Also, the 'wounded on the pendulum' effect is getting doubled for some reason (-1 ref is becoming -2). I've created other effects on this character with -1 ref, and they work normally. I suspect it's because the wounded on the pendulum effect has expired several times due to passing combat turns, and been replaced. 

[fvtt-Item-cat-potion-(copy)-jORXcwgddEFFAPHe.json](https://github.com/user-attachments/files/17878270/fvtt-Item-cat-potion-.copy.-jORXcwgddEFFAPHe.json)
When consumed, this potion creates the effect on the user as it is supposed to. However, the duration is only 1 round. And if I increase the duration, and pass several combat rounds, I suspect the duration will be subtracted from all future uses of the potion as well.
![Screenshot 2024-11-22 191644](https://github.com/user-attachments/assets/dfdbe39c-5233-4689-9fb6-8621c7de31b0)

**Comment by Stexinator** [comment]
The effects are deleted by status effect counter modules
