### ISSUE TITLE
[BUG] Un-aimed attacks not accurately reporting the target location

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#225]
**Describe the bug**
Attacks that are not aimed report "random" as their target location instead of whatever location is rolled.

**To Reproduce**
Use any actor's attack roll, and choose random location.

**Expected behavior**
It used to tell you which location was hit by a random location attack.

**Screenshots**
![Screenshot 2024-11-22 091014](https://github.com/user-attachments/assets/616cbcce-2cb7-4595-a66e-ebf359a68797)

**Versions (please complete the following information):**
 - Foundry Version 12.331
 - Version 12.13.0 and 12.14.0 

**Additional context**
Mechanics automation still functions properly e.g. damage application.

**Comment by Stexinator** [comment]
That is actually a new feature

**Comment by joridin** [comment]
[fvtt-Actor-vagra-of-zerrikania-VmVf8gZFI1YuahxK.json](https://github.com/user-attachments/files/17878232/fvtt-Actor-vagra-of-zerrikania-VmVf8gZFI1YuahxK.json)
Prediction: if placed into a combat and a turn and/or full round is passed, the three effects highlighted by the red circle will vanish.

[fvtt-Item-blizzard-potion-(copy)-1hFyZC9EyS4fZwjp.json](https://github.com/user-attachments/files/17878268/fvtt-Item-blizzard-potion-.copy.-1hFyZC9EyS4fZwjp.json)
This custom blizzard is now acting even more strangely for me. Even though it is marked as a consumable, when put into a character's inventory, its effects are given to the actor. When consymed, the effects disappear.

[fvtt-Item-cat-potion-(copy)-jORXcwgddEFFAPHe.json](https://github.com/user-attachments/files/17878270/fvtt-Item-cat-potion-.copy.-jORXcwgddEFFAPHe.json)
Cat, on the other hand, is displaying the bug as I described it. When consumed, it creates the effect on the user as it is supposed to. However, the duration is only 1 round. And if I increase the duration, and pass several combat rounds, I suspect the duration will be subtracted from all future uses of the potion as well.
![Screenshot 2024-11-22 191644](https://github.com/user-attachments/assets/dfdbe39c-5233-4689-9fb6-8621c7de31b0)

**Comment by joridin** [comment]
Nevermind the blizzard. I found i had switched the boxes from activate on use to activate on possession. Still, when consumed, the duration always resets to 1 round.

**Comment by Hankhoff** [comment]
> That is actually a new feature tied into rerolling for crits and applying active effects that add to the roll

is there a way to still auto-roll the location? it would really make my life easier the way my group plays the game

**Comment by Stexinator** [comment]
The location is still auto-rolled. It just says random instead of the exact location string

**Comment by Hankhoff** [comment]
Sorry, i still dont get the use. Is there any way to determine the Hit location drom the chat to see if it hits the legs or arms? i mean i cant see it from the damage modifier alone
