### ISSUE TITLE
[BUG] Template and region not working

### ISSUE THREAD

**Issue by KleinNoob** [witchertrpg-foundryvtt/TheWitcherTRPG#226]
When I cast a spell the template area doesn't show
![imagem_2024-11-23_174332528](https://github.com/user-attachments/assets/3d202746-ba20-43d6-b7dd-f4ad9a873aee)

Foundry v12.331
The Witcher TRPG v12.14.0

**Comment by Stexinator** [comment]
Cannot reproduce. Can you provide more info?
