### ISSUE TITLE
[BUG] Non-Lethal Damage is Ablating Armor

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#229]
**Non-Lethal Damage is Ablating SP it Bypasses**
When non-lethal damage bypasses SP, it reduces the SP by a point as though it were lethal damage.

**To Reproduce**
1. Create a Weapon Item that uses Non-Lethal Damage
2. Roll non-lethal damage that surpasses the SP of an Armor Item
3. Apply the damage to an Actor with the Armor Item equipped
4. Check the current SP value of the equipped Armor Item

**Expected behavior**
Non-lethal damage should not reduce an Armor's SP.

**Versions (please complete the following information):**
 - Foundry Version v12.331
 - v.12.14.0

**Comment by Stexinator** [comment]
Works as intended.

If you want to say there is a rule that non-lethal armor does not ablate I need the rule reference
