### ISSUE TITLE
[BUG] URGENT: NPC Custom HP/STA not working

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#240]
**Describe the bug**
When the checkbox for Custom HP/STA is selected in an NPC Actor sheet, it defaults the HP max to normal and sets STA max to 0.

**Expected behavior**
It should accept the custom HP max and STA max values.

**Comment by Stexinator** [comment]
Duplicate of https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/232
