### ISSUE TITLE
[BUG] Head damage that is lower than the token's armor is not applied correctly.

### ISSUE THREAD

**Issue by pedroaugustobt** [witchertrpg-foundryvtt/TheWitcherTRPG#244]
**Describe the bug**
Example: My NPC rolled an 8 with his Bow aimed at the head. The enemy NPC has 20 armor. The head damage would be 8 * 3 = 24, but it is not applied correctly.

**Expected behavior**
The NPC should take 4 damage and his armor should reduce by 1

**Screenshots**
![image](https://github.com/user-attachments/assets/37fbf402-b3c6-45b2-a714-4985418046a8)

**Versions (please complete the following information):**
 - Foundry Version [e.g. v12.331]
 - Version The Witcher TRPG [e.g. 12.14.1]

**Comment by Stexinator** [comment]
The head damage is (8-20)*3 = 0

Page 153 CRB
