### ISSUE TITLE
[BUG] URGENT: NPC Custom HP/STA Still not working

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#245]
**Describe the bug**
When the checkbox for Custom HP/STA is selected in an NPC Actor sheet, it defaults the HP max to normal and sets STA max to 0.

**Expected behavior**
It should accept the custom HP max and STA max values.

**Versions (please complete the following information):**
 - Version 12.15.0

**Comment by Stexinator** [comment]
There is an arrow now where you can set the custom fields

![grafik](https://github.com/user-attachments/assets/c748ed59-415c-4338-95b9-fc15a1581d55)

**Comment by Siryphas** [comment]
No. It does not hold the value for HP. STA works now, but the HP defaults as soon as I close the sheet.
