### ISSUE TITLE
[BUG] Problems with automated damage from status effects

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#250]
**Describe the bug**
When a token/actor is both poisoned and bleeding, the system tries to apply damage for both, but only the damage value for the more recently added status effect is deducted from actor hp.
If burning is added to the mix, the burning damage is not taken from the hp if the condition was added before the bleeding or poison. If burning was the most recently added status effect, it will be deducted from the actor hp, along with poison **or** bleeding, whichever of the two was more recently added than the other.
The +3 hp per turn from healing status effect doesn't seem to work.

 - Foundry  v12.331
 - Witcher TTRPG 12.14.0-12.15.1

**Comment by Stexinator** [comment]
Healing is not automated due to it not always being +3
