### ISSUE TITLE
[FEATURE] Monsters can equip weapons/attacks

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#256]
**Is your feature request related to a problem? Please describe.**
Currently monsters can not equip their weapons or attacks, which means any active effects their weapon/attack items apply to them are stuck in inactive mode.
 
**Describe the solution you'd like**
Make it so monster sheet weapons/attacks can be equipped. 

**Describe alternatives you've considered**
Creating non-weapon items in the monster inventory to emulate the effects, which can be toggled on or off in active effects.

**Additional context**
![Screenshot 2024-12-18 091022](https://github.com/user-attachments/assets/a8f9bf7f-d184-484f-bfc1-f782f7e0725a)
Note that the balanced weapon effect is marked 'on' (with an x to turn it off, instead of a checkmark to turn it on) but it is in the inactive category.

**Comment by Stexinator** [comment]
Effects from un-equipped items are inactive, even if they are active on the item

**Comment by Stexinator** [comment]
Monsters will auto-equip weapons when they are dropped on the actor with v12.15.3
