### ISSUE TITLE
[FEATURE] Stop the Custom HP/STA menu from closing every entry

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#259]
**Is your feature request related to a problem? Please describe.**
Right now when a value is entered into the Custom HP/STA sub-menu, it closes on its own. While it isn't a *major* issue, it is quite tedious when making multiple edits. 

**Describe the solution you'd like**
If there is some way to design the sub-menu to remain open until it's manually closed, that would be very helpful.

**Comment by Stexinator** [comment]
This is foundry behaviour. There is nothing I can do about that
