### ISSUE TITLE
[BUG] Effect Percentages Zeroing

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#262]
**Describe the bug**
Some of the Status Effects, such as Stun and Unconcious are not accepting percentage values and remain at 0.

**To Reproduce**
1. Go to Spell Item sheet.
2. Add an effect and try to place a percentage value.
3. See error

**Expected behavior**
The Percentage value should function regardless of the Status Effect selected in order to get the spell/weapon to trigger the effect on a targeted token.

**Comment by Stexinator** [comment]
![grafik](https://github.com/user-attachments/assets/313d3513-fbfc-40e5-b95d-cba66d8ecd0d)

I dont see a problem here
