### ISSUE TITLE
[BUG] Hexes and rituals not rolling from sheet

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#268]
**Describe the bug**
Clicking on an actor's hexes or rituals on their character sheet does not roll the skill as it used to. This has been tested with pre-update as well as newly created hexes and rituals.

**Screenshots**
![Screenshot 2024-12-31 053416](https://github.com/user-attachments/assets/0fd8967b-9059-4da0-ac28-e8b04e931bc9)
These buttons do nothing.

**Versions (please complete the following information):**
 - Foundry v12.331
 - Witcher TTRPG  v12.16.0

**Comment by Stexinator** [comment]
Can you check for errors in the console?
