### ISSUE TITLE
Fear Status Icon

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [witchertrpg-foundryvtt/TheWitcherTRPG#34]
> The feared condition doesn't have a token icon

> I can reproduce it on v11. Might well be the image. Do you have an alternate art for hallucination?

> Cheers for including this as an effect - I don't think there are any rules for Fear, bar what has been home brewed via Reddit? Happy to post what we use in our game here, if that's useful? Or for a Wikki? 
>It doesn't actually exist, but fear is mentioned in Tome of Chaos, 74, theres a Minor Gift called Fear Aura, which says that Fear adds a -2 to all actions against you.

**Comment by Stexinator** [comment]
@Siryphas you wanted to provide an alternative image :) Any luck with finding something suitable?

**Comment by Siryphas** [comment]
I would probably use the default Icon, which this system is using for Hallucination. 
Hallucination could use this image, or something like it.
![hallucination-icon-line-art-style-260nw-2139719127](https://github.com/user-attachments/assets/aca7a6ee-827a-4851-a5e1-8691a92c4b45)
