### ISSUE TITLE
Damage Roll Pop Up

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#4]
Could we get a feature that would add a Pop-Up to the Damage button in the chat, allowing us to edit the number of d6's used in Spells? This would fix the issues for Alzur's Thunder (Declining Damage) as well as the other spells that have Variable Damage based on Difference. 
If when we clicked the Damage button and it came up and asked to verify the damage, we could then adjust Alzur's Thunder to do 8d6, 7d6, 6d6, etc. Additionally, we could adjust for spells like Cenlly Graig that can do anywhere from 1d6 to 10d6 damage.

**Comment by Stexinator** [comment]
Sounds doable
