### ISSUE TITLE
Global Modifiers break rolls if using certain characters in their names

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#45]
Global modifiers for spells in the compendium use square brackets, e.g. "Glamour [Effect]". Square brackets and certain other characters seem to break skill rolls that they apply to, so with Glamour [Effect] active, you wouldn't be able to roll Charisma, Leadership, or Seduction.

**Comment by Stexinator** [comment]
Is the modifier already on the sheet? Which version of the system are you using? 

All versions from this repository have the compendium removed and in the next version a bug with compendium effects is fixed that would fit your description.

**Comment by Stexinator** [comment]
I can reproduce it. The problem is nested [ ]

@Siryphas can you change that in the compendium? Foundry forbids nesting these symbols

**Comment by joridin** [comment]
i still had the compendiums left over from previous versions since the
system didn't delete them on update.

**Comment by Siryphas** [comment]
Yeah I can fix it

**Comment by Stexinator** [comment]
@joridin you can manually delete the **_italic fat_** text. Then it works again. If it is a bigger issue for you, you need to raise a bug with foundry so that the peggy parsing allows nested brackets

**Comment by joridin** [comment]
i'd already changed effect names to remove the square brackets. just
thought i'd mention the issue for future reference. unless there's
somewhere else i should raise compendium specific problems.

**Comment by Stexinator** [comment]
The compendium moved to https://github.com/Siryphas/Witcher-Compendium As far as I know this is the most complete one and Siryphas tries to be as fast as possible to update it to new system functionality
