### ISSUE TITLE
Cannot add effects to armour

### ISSUE THREAD

**Issue by OscarMeFer** [witchertrpg-foundryvtt/TheWitcherTRPG#55]
The button for add effect and the gear in the left-up side, not work

**Comment by Stexinator** [comment]
The gear in the left-up side is without function yet, due to armors not needing a dedicated configuration sheet

**Comment by OscarMeFer** [comment]
Ok, I understand, but the ‘+’ button doesn't work either! :(

**Comment by Stexinator** [comment]
Both things will be fixed in the next version
