### ISSUE TITLE
Right-Click chat Critical Wounds, Locations Randomized

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#68]
So, when you use the right-click in chat feature to apply a Critical Wound to an actor, it seems to always default to the location hit. Per the RAW, this should only be the case if the attack is aimed. Otherwise, the Critical Wound should determine the hit location if the attack was not aimed.
When I ran our session last night, there were five Crits and they always applied a wound to the same location the system rolled, regardless of whether the actor aimed for that location or not. I know the system automatically rolls for location with the attack roll, but mechanically, this isn't how it should be working in regard to Critical Wounds.

**Comment by Stexinator** [comment]
This is known. The system currently does not know if the location was randomly determined or not. At the point of the crit the location is already set. 

To do it the mechanical correct way it would need to change the location after realising that it is a crit. This would be confusing for the user do to the difference in the chat messages.

The real difference is mathematical not very big. It makes criticals on the head happen slightly more often.
