### ISSUE TITLE
Update german translations - structure

### ISSUE THREAD

**Issue by Stexinator** [witchertrpg-foundryvtt/TheWitcherTRPG#69]
The english translation file was re-structured. The same should happen to the german translation file

**Comment by Stexinator** [comment]
When this is done it should be easier to see which content is missing.

@LinkDragmire do you want to give it a shot?

**Comment by LinkDragmire** [comment]
Is there a reason to differentiate between left and right hand in the weapons section? no problem to translate, but seems like just additional work in configuring items

**Comment by LinkDragmire** [comment]
This could be closed now, if anyone discovers a missing or wrong translation for the german version, you could highlight me ;)
