### ISSUE TITLE
Setting that wounds afflict skill base instead of skill

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#73]
Currently, certain severe wounds only half or quarters the final value of the base skill roll formula (i.e. the skill level itself). So if your roll would be, say 1d10+4 (DEX)+4 (Athletics), the wound would only half or quarter the last 4 (to 2 or 1), resulting in a -2 or -3.

I think such wounds are supposed to apply to the entire value of the skill base (stat + skill), or maybe even to an entire roll total (1d10 + stat + skill). My weaker reason for thinking this is that the system is generally concerned with the operation of skill bases rather than isolating just the skill level. My much stronger reason for thinking this is that the lesser wounds apply their -1, -2, -3 or whatever to the roll total, and applying the halving or quartering effect only to the skill level can result in an upgrade. Say you have a REF of 10, but a Dodge/Escape level of 0. Going from a sprained leg to a dismembered leg would actually improve your dodging skills! (you'd go from a -2 to a -0, or a base 8 back to base 10, because there's no Dodge/Escape value to divide).

I was asked to raise this as a new issue.

**Comment by Stexinator** [comment]
Thanks for opening it as a separate issue. The wording is just ``skill`` and not ``skill base``. If you got an errata or sage advice that you could link I would be willing to change that. 

As long as no official word is out I have to keep it as raw as possible which means applying it just as a skill. Your examples are extreme and the system has several weak points when looking at extremes, so I would not wonder when this behaves as expected

**Comment by joridin** [comment]
well we're not going to be getting any official word on anything for a decade or so. oh well
