### ISSUE TITLE
Improved Armor Piercing Rounding

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#84]
Improved Armor Piercing is reducing to decimals, rather than rounding up.

**Comment by Stexinator** [comment]
Can you add the current status and the expected status?

**Comment by Siryphas** [comment]
If SP is 11, Improved Amor Piercing reduces it to 5.5, it should round down to 5.

**Comment by Stexinator** [comment]
Can you cite a sage or rule passage for that?

**Comment by Siryphas** [comment]
> Can you cite a sage or rule passage for that?

There isn't a specific line of text that says this, but the general design of the game is that all decimals round down, including damage. So, if a weapon treats SP as half in terms of damage, it would be the damage that's rounded down; and thus the SP that would be rounded up.
This is the same way that damage is rounded for Resistances and for Limb damage modifications.
