### ISSUE TITLE
Add Ability To Add Extra Dice To Weapon Rolls

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [witchertrpg-foundryvtt/TheWitcherTRPG#86]
In the pop up when you roll a weapon it would be nice to be able to enter a number of d6 to add to the damage roll, or add it to the pop up when you hit the damage button from chat. It would be useful for things like when you charge on a horse and it adds in more dice to the attack.

**Comment by Stexinator** [comment]
This can be done with variable damage

**Comment by AlexanderTheGr3at** [comment]
> This can be done with variable damage

Don't those only pop up for things that have variable damage? Because If I just use a normal sword it doesn't have variable damage  (and so I don't get a chance to add extra die), but if I swing it on a charging horse it does add extra damage because of the speed, I don't get a pop up though because the weapon itself doesn't have variable damage.

**Comment by Stexinator** [comment]
Variable Damage is a settings that can be done on any weapon or spell. If you want to have the popup for a session you can configure it and remove it afterwards again

**Comment by AlexanderTheGr3at** [comment]
> Variable Damage is a settings that can be done on any weapon or spell. If you want to have the popup for a session you can configure it and remove it afterwards again

I tested this, you think I would have remembered that. God I'm dumb lol. Sorry!
