### ISSUE TITLE
Mount "items" add their weight to owner's encumbrance

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#96]
It's an old issue among long time players that the 'weight' column for mounts and vehicles in the gear lists is ambiguous. Is it supposed to be the actual weight of the mount or vehicle? Or is it supposed to be how much weight it can carry? The problem is: the numbers are wrong, either way. Adult horses are most certainly not 100kg. Yet it does not match their ENC as shown in the beastiary, either (120 kg).

However, the numbers are probably supposed to represent the ENC value, for a couple of reasons. One, the numbers are much closer, and discrepancies can be explained by a failure to cross-reference when making errata or updates. Two, this information is far more useful for players. You'll almost always need to know how much your animal or vehicle can carry, since you'll be using it to carry things, or riding it. You'll much less often need to know how heavy the thing itself is.

So perhaps the "weight" of the mount or vehicle "item" should not be counted toward the owner's encumbrance. Either that, or add the "carried" toggle to mount items. Although the mental image of characters carrying all of their horses and mules around like giant babies is pretty funny,

**Comment by Stexinator** [comment]
There is a checkbox to ignore this for weight calculation
