### ISSUE TITLE
Removing Armor Enhancements

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#97]
There doesn't seem to be a way to remove an Armor Enhancement once it has been applied to an armor, even though RAW they should be removable.

**Comment by Stexinator** [comment]
What happens when you remove it?

**Comment by Siryphas** [comment]
There doesn't seem to be any way to remove it. Unless I've missed something.

**Comment by Stexinator** [comment]
I meant in the rules, CRB p.90. The enhancement should be added to the inventory afterwards

**Comment by Siryphas** [comment]
Oh, yes. Sorry, I misunderstood. It should return to the inventory and maybe used on other items later.
